import type { LucideIcon } from "lucide-react";

import {
  AlignLeft,
  ArrowLeft,
  ArrowRight,
  AtSign,
  Book,
  Bookmark,
  BookOpen,
  Box,
  Boxes,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  Clock,
  Code2,
  Compass,
  Container,
  Copy,
  CornerDownLeft,
  Cpu,
  CreditCard,
  Database,
  Diamond,
  Download,
  ExternalLink,
  FileText,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  Grid2x2,
  Grid3x3,
  Heart,
  HeartPulse,
  Home,
  Image,
  Laptop,
  Layers,
  LayoutGrid,
  Link2,
  ListCheck,
  Lock,
  LogIn,
  Mail,
  MapPin,
  Menu,
  Monitor,
  Moon,
  Mouse,
  Package,
  PanelLeft,
  Pin,
  Plus,
  Quote,
  Rocket,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Target,
  Terminal,
  TrendingUp,
  Trophy,
  Truck,
  User,
  UserPlus,
  Watch,
  X,
  Zap,
} from "lucide-react";

export const lucideIcons = {
  // Navigation
  home: Home,
  menu: Menu,
  close: X,
  "panel-left": PanelLeft,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  download: Download,
  "corner-down-left": CornerDownLeft,

  // Actions
  add: Plus,
  check: Check,
  copy: Copy,
  search: Search,
  share: Share2,
  shuffle: Shuffle,
  "log-in": LogIn,

  // Content
  "file-text": FileText,
  folder: Folder,
  book: Book,
  "book-open": BookOpen,
  bookmark: Bookmark,
  quote: Quote,
  image: Image,
  link: Link2,
  "align-left": AlignLeft,

  // Users
  user: User,
  "user-plus": UserPlus,
  mail: Mail,
  mouse: Mouse,
  "at-sign": AtSign,

  // Commerce
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  package: Package,
  shirt: Shirt,
  watch: Watch,
  "credit-card": CreditCard,
  truck: Truck,

  // Technology
  code: Code2,
  cpu: Cpu,
  database: Database,
  server: Server,
  terminal: Terminal,
  monitor: Monitor,
  container: Container,
  box: Box,
  flask: FlaskConical,
  "external-link": ExternalLink,
  boxes: Boxes,
  layers: Layers,

  // Status & Feedback
  "circle-check": CircleCheck,
  "check-circle": CheckCircle2,
  clock: Clock,
  lock: Lock,
  shield: Shield,

  // UI & Layout
  sliders: SlidersHorizontal,
  settings: Settings,
  "grid-small": Grid2x2,
  "grid-medium": Grid3x3,
  "layout-grid": LayoutGrid,

  // Marketing & Highlights
  flame: Flame,
  sparkles: Sparkles,
  star: Star,
  rocket: Rocket,
  target: Target,
  trophy: Trophy,
  "trending-up": TrendingUp,

  // Location & Planning
  calendar: Calendar,
  "map-pin": MapPin,
  compass: Compass,
  flag: Flag,

  // Theme
  moon: Moon,
  sun: Sun,

  // Miscellaneous
  heart: Heart,
  "heart-pulse": HeartPulse,
  diamond: Diamond,
  "flask-conical": FlaskConical,
  "list-checks": ListCheck,
  zap: Zap,
  pin: Pin,
  laptop: Laptop,
} satisfies Record<string, LucideIcon>;

export type LucideIconName = keyof typeof lucideIcons;
