import type { Dirent } from "node:fs";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import postcss from "postcss";

// Project root
const ROOT_DIR = process.cwd();

// Styles
const STYLES_DIR = path.join(ROOT_DIR, "src", "styles");

// Source themes
const THEMES_DIR = path.join(STYLES_DIR, "themes", "color-themes");

const CUSTOM_THEMES_DIR = path.join(STYLES_DIR, "themes", "custom-themes");

// Generated themes
const GENERATED_DIR = path.join(STYLES_DIR, ".generated");

const GENERATED_THEMES_DIR = path.join(GENERATED_DIR, "themes");

type ThemeEntry = {
  entry: Dirent;
  directory: string;
};

const scopeThemeCss = (name: string, css: string): string => {
  const root = postcss.parse(css);

  let matched = false;

  root.walkRules((rule) => {
    const selector = rule.selector.trim();

    if (selector === ":root") {
      rule.selector = `[data-theme="${name}"]`;
      matched = true;
      return;
    }

    if (selector === ".dark") {
      rule.selector = `[data-theme="${name}"].dark`;
      matched = true;
    }
  });

  if (!matched) {
    console.warn(
      `[themes] ${name}.css has no top-level :root or .dark rule to scope.`,
    );
  }

  return root.toString();
};

const readThemeEntries = async (directory: string): Promise<ThemeEntry[]> => {
  const entries = await readdir(directory, {
    withFileTypes: true,
  });

  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".css"))
    .map((entry) => ({
      entry,
      directory,
    }));
};

const run = async () => {
  const entries: ThemeEntry[] = [
    ...(await readThemeEntries(THEMES_DIR)),
    ...(await readThemeEntries(CUSTOM_THEMES_DIR)),
  ];

  if (entries.length === 0) {
    console.warn("[themes] No theme CSS files found.");
    return;
  }

  await mkdir(GENERATED_THEMES_DIR, {
    recursive: true,
  });

  const themeFiles: string[] = [];

  for (const { entry, directory } of entries) {
    const fileName = entry.name;
    const themeName = path.parse(fileName).name;

    const sourcePath = path.join(directory, fileName);

    const rawCss = await readFile(sourcePath, "utf8");

    const scopedCss = scopeThemeCss(themeName, rawCss);

    await writeFile(
      path.join(GENERATED_THEMES_DIR, fileName),
      scopedCss,
      "utf8",
    );

    themeFiles.push(fileName);

    console.log(`[themes] Generated ${fileName} → [data-theme="${themeName}"]`);
  }

  themeFiles.sort();

  const aggregator = [
    "/* AUTO-GENERATED by build-themes.ts. Do not edit. */",
    ...themeFiles.map((fileName) => `@import "./themes/${fileName}";`),
    "",
  ].join("\n");

  await writeFile(
    path.join(GENERATED_DIR, "theme-imports.css"),
    aggregator,
    "utf8",
  );

  console.log(
    `[themes] Wrote theme-imports.css (${themeFiles.length} theme(s))`,
  );
};

run().catch((error: unknown) => {
  console.error("[themes] Failed to build themes:", error);

  process.exit(1);
});
