/**
 * models-sync.ts — keeps `models.manifest.ts` in step with `public/models`.
 *
 * Runs automatically before `dev` and `build`. It also prints a short report
 * so a new/oversized model is noticed immediately:
 *   - which registry slots still use a placeholder (file missing)
 *   - files over the size budget
 *   - GLBs in public/models that no registry entry uses
 */

import { mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { MODELS } from "../configs/model3d.config";

const ROOT = process.cwd();
export const MODELS_DIR = path.join(ROOT, "public", "models");
const MANIFEST = path.join(
  ROOT,
  "src",
  "packages",
  "configs",
  "models.manifest.ts",
);

/** Soft budget per file. The hero is allowed a little more. */
const BUDGET_BYTES = 1_500_000;
const HERO_BUDGET_BYTES = 2_500_000;

type Entry = { file: string; bytes: number };

const render = (entries: readonly Entry[]) => {
  const body =
    entries.length === 0
      ? "[]"
      : `[\n${entries
          .map((e) => `  { file: "${e.file}", bytes: ${e.bytes} },`)
          .join("\n")}\n]`;

  return `// AUTO-GENERATED by \`bun run models:sync\` — do not edit by hand.
// Lists the GLB files that exist in public/models so the app never requests
// a missing file (it renders the placeholder instead).
export const MODEL_FILES: readonly { file: string; bytes: number }[] = ${body};
`;
};

const kb = (bytes: number) => `${(bytes / 1024).toFixed(0)} KB`;

export const syncManifest = async (quiet = false) => {
  await mkdir(MODELS_DIR, { recursive: true });

  const names = (await readdir(MODELS_DIR))
    .filter((name) => name.toLowerCase().endsWith(".glb"))
    .sort();

  const entries: Entry[] = [];
  for (const file of names) {
    entries.push({
      file,
      bytes: (await stat(path.join(MODELS_DIR, file))).size,
    });
  }

  const next = render(entries);
  const current = await readFile(MANIFEST, "utf8").catch(() => "");
  if (current !== next) await writeFile(MANIFEST, next, "utf8");

  if (quiet) return entries;

  const byFile = new Map(entries.map((e) => [e.file, e.bytes]));
  const used = new Set<string>();

  console.log("[models] registry");
  for (const model of MODELS) {
    used.add(model.file);
    const bytes = byFile.get(model.file);
    if (bytes === undefined) {
      console.log(
        `  · ${model.key.padEnd(20)} placeholder (${model.file} not found)`,
      );
      continue;
    }
    const budget =
      model.key === "hero-workstation" ? HERO_BUDGET_BYTES : BUDGET_BYTES;
    const flag = bytes > budget ? `  ⚠ over budget (${kb(budget)})` : "";
    console.log(
      `  ✓ ${model.key.padEnd(20)} ${model.file} ${kb(bytes)}${flag}`,
    );
  }

  for (const file of names) {
    if (!used.has(file)) {
      console.warn(
        `[models] warning: public/models/${file} is not in model3d.config.ts`,
      );
    }
  }

  return entries;
};

// Run directly (`bun run models:sync`), but stay silent when imported by models-optimize.
if (process.argv[1]?.endsWith("models-sync.ts")) {
  syncManifest().catch((error: unknown) => {
    console.error("[models] sync failed:", error);
    process.exit(1);
  });
}
