// AUTO-GENERATED by `bun run models:sync` — do not edit by hand.
// Lists the GLB files that exist in public/models so the app never requests
// a missing file (it renders the placeholder instead).
export const MODEL_FILES: readonly { file: string; bytes: number }[] = [
  { file: "work-station.glb", bytes: 1080000 },
];
