import type { Project } from "@/types/projects";

const fullstackApps = [
  {
    key: "cloak-shield-web",
    title: "Cloak Shield",
    role: "Full Stack Developer",
    client: "team",
    description:
      "A developer-focused authentication product and marketing site: Next.js on the front, a Hono API behind it, and Supabase and MySQL handling identity, sessions, and user data.",
    tags: [
      "Next.js",
      "TypeScript",
      "Hono",
      "Supabase",
      "MySQL",
      "Tailwind CSS",
      "Vercel",
    ],
    keywords: [
      "authentication",
      "authorization",
      "next-auth",
      "hono",
      "user-management",
      "session-management",
      "backend-api",
      "full-stack",
      "nextjs",
      "supabase",
      "mysql",
    ],
    href: "https://cloak-shield-web.vercel.app/",
    createdAt: "30/08/2026",
    updatedAt: "ongoing",
    coverImage: "/images/cover/cloakshield-cover.png",
  },

  {
    key: "six-teal-store",
    title: "Six Teal Store",
    role: "Full Stack Developer",
    client: "team",
    description:
      "A modern e-commerce storefront with product discovery, persistent cart management, and animated shopping flows, backed by a scalable Supabase and PostgreSQL stack.",
    tags: [
      "Next.js",
      "TypeScript",
      "Supabase",
      "PostgreSQL",
      "Zustand",
      "Tailwind CSS",
      "GSAP",
      "Vercel",
    ],
    keywords: [
      "ecommerce",
      "online-store",
      "product-catalog",
      "cart-management",
      "zustand",
      "full-stack",
      "nextjs",
      "supabase",
      "postgresql",
      "responsive-ui",
    ],
    href: "https://sixteal.vercel.app/",
    createdAt: "30/09/2025",
    updatedAt: "ongoing",
    coverImage: "/images/cover/sixteal-cover.png",
  },
  {
    key: "sparkverse",
    title: "Sparkverse",
    role: "Full Stack Developer",
    client: "team",
    description:
      "A tech news platform covering AI, startups, CEO insights, developer conversations, and gaming, with a content-first reading experience built on Supabase and PostgreSQL.",
    tags: [
      "Next.js",
      "TypeScript",
      "Supabase",
      "PostgreSQL",
      "Tailwind CSS",
      "GSAP",
      "Vercel",
    ],
    keywords: [
      "tech-news",
      "technology",
      "ai",
      "startups",
      "ceo-insights",
      "developer-news",
      "gaming",
      "full-stack",
      "nextjs",
      "supabase",
      "postgresql",
    ],
    href: "https://sparkverse.in/",
    createdAt: "02/02/2026",
    updatedAt: "ongoing",
    coverImage: "/images/cover/sparkverse-cover.png",
  },
] satisfies Project[];

export default fullstackApps;
